### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [GoldenAppleGuy/stats_lab_api#1]
Hello! Will this be updated? Your .csv works a lot better for extraction than the one that OWLCharts has.

**Comment by GoldenAppleGuy** [comment]
Issue is that, starting with the next week after Week 15, Week 18, the API I was grabbing the stats from started to break. Namely, any stats from Illari or Flashpoint maps were not captured. I might still go ahead and compile them if the API is still active. Will update this issue if that happens.

**Comment by ghost** [comment]
How do you access the api? api.overwatchleague.com seems to be down, and OWLCharts is on his tour of pretending to quit again. Also, do you have any suggestions on extraction? I'm a caveman and have been using this since I started watching Overwatch League: https://www.reddit.com/r/Competitiveoverwatch/comments/fcvrys/a_player_stats_viewer_based_on_csv_files_from/

**Comment by ghost** [comment]
OWLCharts for some idiotic reason chose to delete some stats from his own personal .csv like flux efficiency. He also added some of his own like first deaths.

**Comment by GoldenAppleGuy** [comment]
I went about writing a Python program that could interface with it. Documentation is [here](https://develop.battle.net/documentation/owl/community-apis). I'm dusting off the code, as the API still seems to be functional.

**Comment by ghost** [comment]
Will this include new stats like first death and first kills? I can give you the .csv data that OWLCharts uses - though he, for some reason, decided to re-write them into his own columns: https://drive.google.com/drive/folders/13bmc24PFROFqyUPtEaHboZF4lY51XXEE?usp=sharing

**Comment by ghost** [comment]
Also, if you're going to use OCR one day, OWLCharts and I talked about it once:
"You can get stats lab data from the stats lab site, that part is easy, just download the CSVs Winstons lab has an API that you can call to get the timestamped kill feed I poked around teh site and used the dev tools to figure out how to use the API, can def send you some sample code tonight if you need it they use different hero names and player names (casing for player names, hero names are all differen't, so you need to maintain a translation map and convert 1 of them so they match) you also need to use match date and teams participating to join on to sync match IDs once you've done all that you now have both sets of data synced up From there I'd look for stats the correlate with winning. Everything i've found is that the counting stats have causaltiy issues, does having high stats lead to winning or does winning lead to high stats? The things we KNOW are important are first kill and first death rates. then things are are more team independent like accuracy, you can look into the ult stats (build time, efficency, etc) but they also risk running into the problems team dependence. when you look at counting stats, I do think there is value at looking at per 10 and per team fight. Some teams play faster and that can inflate your per 10. But at the same time the game is played with a time clock, so playing faster is often better. (Kinda like the lip convo, his per team fight stats aren't as crazy as his per 10s, but because of how he plays sombra, his teams can take ~2 more team fights per 10 than other teams.) finally if you want to use some AI/ML model, thats perfectly reasonable. Just don't do what IBM did where they throw every single per 10 into a what I believe was catboost and let to spit out its stuff"

**Comment by GoldenAppleGuy** [comment]
First death and first kills would require a log of the killfeed, which is where OCR comes in, yeah. These stats from the API don't allow us to extrapolate that info specifically.

And that's definitely an interesting read. I have been working on an OCR solution similar to Winston's Lab for use in smaller tournaments I'm associated with, so I'll keep that in mind.

**Comment by ghost** [comment]
OWLCharts somehow, though he won't tell me, has first death and first kills on his site. I suspect that some of the data is faked or at least incredibly questionable.

**Comment by ghost** [comment]
https://cdn.discordapp.com/attachments/1133933057091571722/1180982994857644133/image.png?ex=657f671f&is=656cf21f&hm=246ebe624f0c288dcf36c2464193e8a88fe7a1211f55011edf84fca46b959d20&

**Comment by ghost** [comment]
Would you possibly share your OCR?

**Comment by GoldenAppleGuy** [comment]
Still building it, it's nowhere near complete. You'll probably hear about it when it does materialize, though. :)

**Comment by GoldenAppleGuy** [comment]
Updated to Week 19, last available Stats Lab data

**Comment by ghost** [comment]
This isn't an update, but I wanted to ask you a question.

If I wanted to create a rating system from 0 to 100 like Winston's Lab, how would you suggest it? I'm not sure how Barroi did it, but my guess is he normalized it from 0 to 100 in each category and then used some average to add them together.

**Comment by GoldenAppleGuy** [comment]
That's my understanding as well. You'd want to calculate percentiles for different stats and then make some kind of product of those to determine player rating. Could even be done in a spreadsheet with formulas.

**Comment by ghost** [comment]
I'm a dumb idiot, so what do you think about my plan to just take every stat individually and assign a 100 to the highest person and a 0 to the lowest person. Then get a total rating by averaging all the numbers in each category.

Under this idea, it would be lazy math not to manual percentiles, but I don't want to do that because it's pretty hard to tell which stats win games. The only issue with my formula would be finding out which stats are bad when they're higher - like deaths, so the person with the lowest deaths should have a 100 rating. I remember I once had a conversation with Barroi, and he was implying that a high fight win percentage is bad and should be used against a player because they're just being carried by their team

"yeah, if you're Vindaim with average stats and 77% winrate, you know something is wrong lol"
